In [14]:
import pandas as pd

# Define the file path
file_path = '/content/Tamir Hafsa-Salam jaafar-FIN3-DATA (1).xlsx'

# Load the Excel file to inspect sheet names
excel_file = pd.ExcelFile(file_path)
print("Sheet names:", excel_file.sheet_names)

Sheet names: ['Feuil1']

In [15]:
# Read the first sheet and display its head
df = pd.read_excel(file_path, sheet_name=excel_file.sheet_names[0])
display(df.head())
print(df.info())

,Facility,Date of Arrangement,Expiration Date 4/,Amount Agreed,Amount Drawn,Amount Outstanding
0,Flexible Credit Line,"Apr 02, 2025","Apr 01, 2027","3,450,000",0,0.0
1,Resilience and Sustainability Facility,"Sep 28, 2023","Apr 02, 2025","1,000,000",937.5,937.5
2,Flexible Credit Line,"Apr 03, 2023","Apr 02, 2025","3,726,200",0,0.0
3,Precautionary and Liquidity Line,"Dec 17, 2018","Apr 07, 2020","2,150,800","2,150,800",0.0
4,Precautionary and Liquidity Line,"Jul 22, 2016","Jul 21, 2018","2,504,000",0,0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Facility             24 non-null     object
 1   Date of Arrangement  23 non-null     object
 2   Expiration Date 4/   23 non-null     object
 3   Amount Agreed        24 non-null     object
 4   Amount Drawn         24 non-null     object
 5   Amount Outstanding   24 non-null     float64
dtypes: float64(1), object(5)
memory usage: 1.3+ KB
None

In [16]:
import os
import sqlite3
import pandas as pd

# 1. Charger et nettoyer le fichier Excel
file_path = '/content/Tamir Hafsa-Salam jaafar-FIN3-DATA (1).xlsx'
df = pd.read_excel(file_path)

# Nettoyage des colonnes et des données
df.columns = ["facility", "date_of_arrangement", "expiration_date",
              "amount_agreed", "amount_drawn", "amount_outstanding"]

df = df[df["facility"].str.strip().str.lower() != "total"].copy()
df["facility"] = df["facility"].str.strip()

for col in ["date_of_arrangement", "expiration_date"]:
    df[col] = pd.to_datetime(df[col], format="%b %d, %Y").dt.strftime("%Y-%m-%d")

for col in ["amount_agreed", "amount_drawn", "amount_outstanding"]:
    df[col] = pd.to_numeric(df[col].astype(str).str.replace(",", ""))

# 2. Création de la base SQL en mémoire et génération du script
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE facilities (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    facility            TEXT NOT NULL,
    date_of_arrangement DATE NOT NULL,
    expiration_date     DATE NOT NULL,
    amount_agreed       REAL,
    amount_drawn        REAL,
    amount_outstanding  REAL
);
""")

df.to_sql('facilities', conn, if_exists='append', index=False)
conn.commit()

# 3. Affichage du script SQL généré
print("-- SCRIPT SQL GÉNÉRÉ --\n")
for line in conn.iterdump():
    print(line)

conn.close()

-- SCRIPT SQL GÉNÉRÉ --

BEGIN TRANSACTION;
CREATE TABLE facilities (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    facility            TEXT NOT NULL,
    date_of_arrangement DATE NOT NULL,
    expiration_date     DATE NOT NULL,
    amount_agreed       REAL,
    amount_drawn        REAL,
    amount_outstanding  REAL
);
INSERT INTO "facilities" VALUES(1,'Flexible Credit Line','2025-04-02','2027-04-01',3450000.0,0.0,0.0);
INSERT INTO "facilities" VALUES(2,'Resilience and Sustainability Facility','2023-09-28','2025-04-02',1000000.0,937.5,937.5);
INSERT INTO "facilities" VALUES(3,'Flexible Credit Line','2023-04-03','2025-04-02',3726200.0,0.0,0.0);
INSERT INTO "facilities" VALUES(4,'Precautionary and Liquidity Line','2018-12-17','2020-04-07',2150800.0,2150800.0,0.0);
INSERT INTO "facilities" VALUES(5,'Precautionary and Liquidity Line','2016-07-22','2018-07-21',2504000.0,0.0,0.0);
INSERT INTO "facilities" VALUES(6,'Precautionary and Liquidity Line','2014-07-28','2016-07-21',3235100.0,0.0,0.0);
INSERT INTO "facilities" VALUES(7,'Precautionary and Liquidity Line','2012-08-03','2014-07-27',4117400.0,0.0,0.0);
INSERT INTO "facilities" VALUES(8,'Standby Arrangement','1992-01-31','1993-03-31',91.98,18.396,0.0);
INSERT INTO "facilities" VALUES(9,'Standby Arrangement','1990-07-20','1991-03-31',100.0,48.0,0.0);
INSERT INTO "facilities" VALUES(10,'Standby Arrangement','1988-08-30','1989-12-31',210.0,210.0,0.0);
INSERT INTO "facilities" VALUES(11,'Standby Arrangement','1986-12-16','1988-04-30',230.0,230.0,0.0);
INSERT INTO "facilities" VALUES(12,'Standby Arrangement','1985-09-12','1986-12-15',200.0,10.0,0.0);
INSERT INTO "facilities" VALUES(13,'Standby Arrangement','1983-09-16','1985-03-15',300.0,300.0,0.0);
INSERT INTO "facilities" VALUES(14,'Standby Arrangement','1982-04-26','1983-04-25',281.25,281.25,0.0);
INSERT INTO "facilities" VALUES(15,'Extended Fund Facility','1981-03-09','1982-04-25',817.05,136.5,0.0);
INSERT INTO "facilities" VALUES(16,'Extended Fund Facility','1980-10-08','1981-03-08',810.0,147.0,0.0);
INSERT INTO "facilities" VALUES(17,'Standby Arrangement','1971-03-18','1972-03-17',30.0,8.25,0.0);
INSERT INTO "facilities" VALUES(18,'Standby Arrangement','1969-12-15','1970-12-14',25.0,10.0,0.0);
INSERT INTO "facilities" VALUES(19,'Standby Arrangement','1968-10-27','1969-10-26',27.0,10.0,0.0);
INSERT INTO "facilities" VALUES(20,'Standby Arrangement','1967-10-27','1968-10-26',50.0,50.0,0.0);
INSERT INTO "facilities" VALUES(21,'Standby Arrangement','1966-09-23','1967-09-22',50.0,0.0,0.0);
INSERT INTO "facilities" VALUES(22,'Standby Arrangement','1965-09-23','1966-09-22',45.0,0.0,0.0);
INSERT INTO "facilities" VALUES(23,'Standby Arrangement','1959-11-15','1960-11-14',25.0,0.0,0.0);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('facilities',23);
COMMIT;

In [17]:
# SECTION 2 : Connexion à Google Drive
# Utilité : monte ton Google Drive dans Colab et crée un dossier "Colab Datasets"
# pour y garder le fichier Excel, la base de données et le fichier SQL final.
drive.mount('/content/drive')

drive_data_dir = '/content/drive/MyDrive/Colab Datasets'
os.makedirs(drive_data_dir, exist_ok=True)
print("✅ Dossier prêt :", drive_data_dir)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Dossier prêt : /content/drive/MyDrive/Colab Datasets

In [6]:
# SECTION 2 : Connexion à Google Drive
# Utilité : monte ton Google Drive dans Colab et crée un dossier "Colab Datasets"
# pour y garder le fichier Excel, la base de données et le fichier SQL final.
import os
import shutil
from google.colab import drive, files

drive.mount('/content/drive')

drive_data_dir = '/content/drive/MyDrive/Colab Datasets'
os.makedirs(drive_data_dir, exist_ok=True)
print("✅ Dossier prêt :", drive_data_dir)

Mounted at /content/drive
✅ Dossier prêt : /content/drive/MyDrive/Colab Datasets

In [7]:
# SECTION 3 : Charger le fichier Excel
# Utilité : remplace le téléchargement Kaggle du tutoriel. Si le fichier n'est pas encore dans
# le dossier, un bouton d'envoi apparaît : choisis ton fichier Excel. Ensuite pandas le lit
# et le met dans un tableau appelé "df".
nom_fichier = "Tamir_Hafsa-Salam_jaafar-FIN3-DATA.xlsx"
excel_path = os.path.join(drive_data_dir, nom_fichier)

if not os.path.exists(excel_path):
    envoye = files.upload()
    shutil.move(list(envoye.keys())[0], excel_path)

df = pd.read_excel(excel_path)
print(f"✅ Excel chargé : {len(df)} lignes, {len(df.columns)} colonnes\n")
display(df.head())

✅ Excel chargé : 24 lignes, 6 colonnes

,Facility,Date of Arrangement,Expiration Date 4/,Amount Agreed,Amount Drawn,Amount Outstanding
0,Flexible Credit Line,"Apr 02, 2025","Apr 01, 2027","3,450,000",0,0.0
1,Resilience and Sustainability Facility,"Sep 28, 2023","Apr 02, 2025","1,000,000",937.5,937.5
2,Flexible Credit Line,"Apr 03, 2023","Apr 02, 2025","3,726,200",0,0.0
3,Precautionary and Liquidity Line,"Dec 17, 2018","Apr 07, 2020","2,150,800","2,150,800",0.0
4,Precautionary and Liquidity Line,"Jul 22, 2016","Jul 21, 2018","2,504,000",0,0.0

In [8]:
# SECTION 4 : Nettoyer les données
# Utilité : prépare le tableau pour SQL.
#  1. renomme les colonnes (sans espaces ni "4/")
#  2. supprime la ligne "Total" (ce n'est pas un vrai enregistrement)
#  3. enlève les espaces inutiles
#  4. convertit les dates "Apr 02, 2025" en format SQL "2025-04-02"
#  5. convertit les montants "3,450,000" (texte) en vrais nombres
df.columns = ["facility", "date_of_arrangement", "expiration_date",
              "amount_agreed", "amount_drawn", "amount_outstanding"]

df = df[df["facility"].str.strip().str.lower() != "total"].copy()
df["facility"] = df["facility"].str.strip()

for col in ["date_of_arrangement", "expiration_date"]:
    df[col] = pd.to_datetime(df[col], format="%b %d, %Y").dt.strftime("%Y-%m-%d")

for col in ["amount_agreed", "amount_drawn", "amount_outstanding"]:
    df[col] = pd.to_numeric(df[col].astype(str).str.replace(",", ""))

print(f"✅ Données nettoyées : {len(df)} lignes")
display(df.head())

✅ Données nettoyées : 23 lignes

,facility,date_of_arrangement,expiration_date,amount_agreed,amount_drawn,amount_outstanding
0,Flexible Credit Line,2025-04-02,2027-04-01,3450000.0,0.0,0.0
1,Resilience and Sustainability Facility,2023-09-28,2025-04-02,1000000.0,937.5,937.5
2,Flexible Credit Line,2023-04-03,2025-04-02,3726200.0,0.0,0.0
3,Precautionary and Liquidity Line,2018-12-17,2020-04-07,2150800.0,2150800.0,0.0
4,Precautionary and Liquidity Line,2016-07-22,2018-07-21,2504000.0,0.0,0.0

In [9]:
# SECTION 5 : Créer la base de données SQLite et la table
# Utilité : crée la base "imf_facilities.db", définit la structure de la table "facilities"
# (noms et types des colonnes, id automatique), puis y insère toutes les lignes du tableau.
db_path = os.path.join(drive_data_dir, 'imf_facilities.db')
table_name = 'facilities'

if os.path.exists(db_path):          # repartir d'une base vide
    os.remove(db_path)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

cursor.execute(f"""
CREATE TABLE {table_name} (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    facility            TEXT NOT NULL,
    date_of_arrangement DATE NOT NULL,
    expiration_date     DATE NOT NULL,
    amount_agreed       REAL,
    amount_drawn        REAL,
    amount_outstanding  REAL
)
""")

df.to_sql(table_name, conn, if_exists='append', index=False)
conn.commit()
print(f"✅ Base créée : {db_path}")
print(f"✅ Table '{table_name}' remplie avec {len(df)} lignes")

✅ Base créée : /content/drive/MyDrive/Colab Datasets/imf_facilities.db
✅ Table 'facilities' remplie avec 23 lignes

In [10]:
# SECTION 6 : Décrire la structure de la base de données
# Utilité : affiche les colonnes de la table (nom, type), le nombre de lignes,
# et pour chaque colonne le nombre de valeurs uniques et de valeurs vides (NULL).
cursor.execute(f"PRAGMA table_info({table_name})")
columns_info = cursor.fetchall()

print("📋 STRUCTURE DE LA TABLE")
print("=" * 60)
display(pd.DataFrame(columns_info, columns=['cid', 'name', 'type', 'notnull', 'dflt_value', 'pk'])[['name', 'type', 'notnull', 'pk']])

cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
print(f"\nTotal des lignes : {cursor.fetchone()[0]}")

print("\n📈 ANALYSE PAR COLONNE")
print("=" * 60)
for col_info in columns_info:
    col_name, col_type = col_info[1], col_info[2]
    cursor.execute(f"SELECT COUNT(DISTINCT {col_name}) FROM {table_name} WHERE {col_name} IS NOT NULL")
    distincts = cursor.fetchone()[0]
    cursor.execute(f"SELECT COUNT(*) FROM {table_name} WHERE {col_name} IS NULL")
    nulls = cursor.fetchone()[0]
    print(f"{col_name} ({col_type}) -> valeurs uniques : {distincts} | NULL : {nulls}")

📋 STRUCTURE DE LA TABLE
============================================================

                  name     type  notnull  pk
0                   id  INTEGER        0   1
1             facility     TEXT        1   0
2  date_of_arrangement     DATE        1   0
3      expiration_date     DATE        1   0
4        amount_agreed     REAL        0   0
5         amount_drawn     REAL        0   0
6   amount_outstanding     REAL        0   0

Total des lignes : 23

📈 ANALYSE PAR COLONNE
============================================================
id (INTEGER) -> valeurs uniques : 23 | NULL : 0
facility (TEXT) -> valeurs uniques : 5 | NULL : 0
date_of_arrangement (DATE) -> valeurs uniques : 23 | NULL : 0
expiration_date (DATE) -> valeurs uniques : 22 | NULL : 0
amount_agreed (REAL) -> valeurs uniques : 21 | NULL : 0
amount_drawn (REAL) -> valeurs uniques : 14 | NULL : 0
amount_outstanding (REAL) -> valeurs uniques : 2 | NULL : 0

In [11]:
# SECTION 7 : Requêtes SELECT (vérifier que la base SQL fonctionne)
# Utilité : lit les données avec de vraies requêtes SQL : (1) tout afficher,
# (2) filtrer les facilités qui ont un montant restant à payer, (3) compter et additionner par type de facilité.
print("1️⃣  SELECT simple")
display(pd.read_sql_query(f"SELECT * FROM {table_name}", conn))

print("2️⃣  SELECT avec filtre : montant restant > 0")
display(pd.read_sql_query(f"SELECT * FROM {table_name} WHERE amount_outstanding > 0", conn))

print("3️⃣  SELECT avec agrégation : par type de facilité")
display(pd.read_sql_query(f"""
SELECT facility,
       COUNT(*)                  AS nb_arrangements,
       ROUND(SUM(amount_agreed), 2) AS total_agreed
FROM {table_name}
GROUP BY facility
ORDER BY nb_arrangements DESC
""", conn))

1️⃣  SELECT simple

,id,facility,date_of_arrangement,expiration_date,amount_agreed,amount_drawn,amount_outstanding
0,1,Flexible Credit Line,2025-04-02,2027-04-01,3450000.00,0.000,0.0
1,2,Resilience and Sustainability Facility,2023-09-28,2025-04-02,1000000.00,937.500,937.5
2,3,Flexible Credit Line,2023-04-03,2025-04-02,3726200.00,0.000,0.0
3,4,Precautionary and Liquidity Line,2018-12-17,2020-04-07,2150800.00,2150800.000,0.0
4,5,Precautionary and Liquidity Line,2016-07-22,2018-07-21,2504000.00,0.000,0.0
5,6,Precautionary and Liquidity Line,2014-07-28,2016-07-21,3235100.00,0.000,0.0
6,7,Precautionary and Liquidity Line,2012-08-03,2014-07-27,4117400.00,0.000,0.0
7,8,Standby Arrangement,1992-01-31,1993-03-31,91.98,18.396,0.0
8,9,Standby Arrangement,1990-07-20,1991-03-31,100.00,48.000,0.0
9,10,Standby Arrangement,1988-08-30,1989-12-31,210.00,210.000,0.0
10,11,Standby Arrangement,1986-12-16,1988-04-30,230.00,230.000,0.0
11,12,Standby Arrangement,1985-09-12,1986-12-15,200.00,10.000,0.0
12,13,Standby Arrangement,1983-09-16,1985-03-15,300.00,300.000,0.0
13,14,Standby Arrangement,1982-04-26,1983-04-25,281.25,281.250,0.0
14,15,Extended Fund Facility,1981-03-09,1982-04-25,817.05,136.500,0.0
15,16,Extended Fund Facility,1980-10-08,1981-03-08,810.00,147.000,0.0
16,17,Standby Arrangement,1971-03-18,1972-03-17,30.00,8.250,0.0
17,18,Standby Arrangement,1969-12-15,1970-12-14,25.00,10.000,0.0
18,19,Standby Arrangement,1968-10-27,1969-10-26,27.00,10.000,0.0
19,20,Standby Arrangement,1967-10-27,1968-10-26,50.00,50.000,0.0
20,21,Standby Arrangement,1966-09-23,1967-09-22,50.00,0.000,0.0
21,22,Standby Arrangement,1965-09-23,1966-09-22,45.00,0.000,0.0
22,23,Standby Arrangement,1959-11-15,1960-11-14,25.00,0.000,0.0

2️⃣  SELECT avec filtre : montant restant > 0

,id,facility,date_of_arrangement,expiration_date,amount_agreed,amount_drawn,amount_outstanding
0,2,Resilience and Sustainability Facility,2023-09-28,2025-04-02,1000000.0,937.5,937.5

3️⃣  SELECT avec agrégation : par type de facilité

                                 facility  nb_arrangements  total_agreed
0                     Standby Arrangement               14       1665.23
1        Precautionary and Liquidity Line                4   12007300.00
2                    Flexible Credit Line                2    7176200.00
3                  Extended Fund Facility                2       1627.05
4  Resilience and Sustainability Facility                1    1000000.00

In [12]:
# SECTION 8 : Générer et télécharger le FICHIER SQL (résultat final)
# Utilité : iterdump() écrit le script SQL complet (CREATE TABLE + tous les INSERT) dans
# "imf_facilities.sql". Le fichier est enregistré dans ton Drive et téléchargé sur ton ordinateur.
sql_path = os.path.join(drive_data_dir, 'imf_facilities.sql')

with open(sql_path, "w", encoding="utf-8") as f:
    for ligne in conn.iterdump():
        f.write(ligne + "\n")

print("✅ Fichier SQL créé :", sql_path)
files.download(sql_path)

✅ Fichier SQL créé : /content/drive/MyDrive/Colab Datasets/imf_facilities.sql

In [ ]:
# SECTION 9 (optionnelle) : Requêtes INSERT, UPDATE, DELETE
# Utilité : montre les opérations CRUD du tutoriel. On ajoute une ligne de test, on la modifie,
# puis on la supprime : la base revient donc exactement à son état d'origine (le fichier SQL
# de la section 8 n'est pas touché).
cursor.execute(f"""
INSERT INTO {table_name} (facility, date_of_arrangement, expiration_date, amount_agreed, amount_drawn, amount_outstanding)
VALUES ('Test Facility', '2026-01-01', '2027-01-01', 1000, 0, 0)
""")
conn.commit()
print("INSERT : ligne de test ajoutée")

cursor.execute(f"UPDATE {table_name} SET amount_drawn = 500, amount_outstanding = 500 WHERE facility = 'Test Facility'")
conn.commit()
print(f"UPDATE : {cursor.rowcount} ligne modifiée")
display(pd.read_sql_query(f"SELECT * FROM {table_name} WHERE facility = 'Test Facility'", conn))

cursor.execute(f"DELETE FROM {table_name} WHERE facility = 'Test Facility'")
conn.commit()
print(f"DELETE : {cursor.rowcount} ligne supprimée")

cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
print("Lignes restantes :", cursor.fetchone()[0])
conn.close()

INSERT : ligne de test ajoutée
UPDATE : 1 ligne modifiée

,id,facility,date_of_arrangement,expiration_date,amount_agreed,amount_drawn,amount_outstanding
0,24,Test Facility,2026-01-01,2027-01-01,1000.0,500.0,500.0

DELETE : 1 ligne supprimée
Lignes restantes : 23

### **Question 1 : Top 5 des arrangements les plus anciens**

In [18]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q1 = """
SELECT facility, date_of_arrangement, expiration_date, amount_agreed
FROM facilities
ORDER BY date_of_arrangement ASC
LIMIT 5;
"""
display(pd.read_sql_query(q1, conn))
conn.close()

              facility date_of_arrangement expiration_date  amount_agreed
0  Standby Arrangement          1959-11-15      1960-11-14           25.0
1  Standby Arrangement          1965-09-23      1966-09-22           45.0
2  Standby Arrangement          1966-09-23      1967-09-22           50.0
3  Standby Arrangement          1967-10-27      1968-10-26           50.0
4  Standby Arrangement          1968-10-27      1969-10-26           27.0

### **Question 2 : Montant moyen accordé par type de facilité**

In [19]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q2 = """
SELECT facility, ROUND(AVG(amount_agreed), 2) AS average_amount_agreed
FROM facilities
GROUP BY facility
ORDER BY average_amount_agreed DESC;
"""
display(pd.read_sql_query(q2, conn))
conn.close()

                                 facility  average_amount_agreed
0                    Flexible Credit Line             3588100.00
1        Precautionary and Liquidity Line             3001825.00
2  Resilience and Sustainability Facility             1000000.00
3                  Extended Fund Facility                 813.52
4                     Standby Arrangement                 118.95

### **Question 3 : Taux de tirage par type de facilité**

In [20]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q3 = """
SELECT facility,
       ROUND(SUM(amount_drawn), 2) AS total_drawn,
       ROUND(SUM(amount_agreed), 2) AS total_agreed,
       ROUND((SUM(amount_drawn) / SUM(amount_agreed)) * 100, 2) || '%' AS draw_rate_pct
FROM facilities
GROUP BY facility;
"""
display(pd.read_sql_query(q3, conn))
conn.close()

,facility,total_drawn,total_agreed,draw_rate_pct
0,Extended Fund Facility,283.5,1627.05,17.42%
1,Flexible Credit Line,0.0,7176200.00,0.0%
2,Precautionary and Liquidity Line,2150800.0,12007300.00,17.91%
3,Resilience and Sustainability Facility,937.5,1000000.00,0.09%
4,Standby Arrangement,1175.9,1665.23,70.61%

### **Question 4 : Arrangements de type « Standby Arrangement »**

In [21]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q4 = """
SELECT facility, date_of_arrangement, expiration_date, amount_agreed
FROM facilities
WHERE facility LIKE '%Stand-By%'
ORDER BY date_of_arrangement;
"""
display(pd.read_sql_query(q4, conn))
conn.close()

Empty DataFrame
Columns: [facility, date_of_arrangement, expiration_date, amount_agreed]
Index: []

### **Question 5 : Statistiques du montant accordé par type de facilité**

In [23]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q5 = """
SELECT facility,
       MIN(amount_agreed) AS min_agreed,
       MAX(amount_agreed) AS max_agreed,
       ROUND(AVG(amount_agreed), 2) AS avg_agreed
FROM facilities
GROUP BY facility;
"""
display(pd.read_sql_query(q5, conn))
conn.close()

                                 facility  min_agreed  max_agreed  avg_agreed
0                  Extended Fund Facility       810.0      817.05      813.52
1                    Flexible Credit Line   3450000.0  3726200.00  3588100.00
2        Precautionary and Liquidity Line   2150800.0  4117400.00  3001825.00
3  Resilience and Sustainability Facility   1000000.0  1000000.00  1000000.00
4                     Standby Arrangement        25.0      300.00      118.95

### **Question 6 : Arrangements dont une partie a été tirée**

In [22]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q6 = """
SELECT facility, date_of_arrangement, amount_agreed, amount_drawn
FROM facilities
WHERE amount_drawn > 0
ORDER BY amount_drawn DESC;
"""
display(pd.read_sql_query(q6, conn))
conn.close()

,facility,date_of_arrangement,amount_agreed,amount_drawn
0,Precautionary and Liquidity Line,2018-12-17,2150800.00,2150800.000
1,Resilience and Sustainability Facility,2023-09-28,1000000.00,937.500
2,Standby Arrangement,1983-09-16,300.00,300.000
3,Standby Arrangement,1982-04-26,281.25,281.250
4,Standby Arrangement,1986-12-16,230.00,230.000
5,Standby Arrangement,1988-08-30,210.00,210.000
6,Extended Fund Facility,1980-10-08,810.00,147.000
7,Extended Fund Facility,1981-03-09,817.05,136.500
8,Standby Arrangement,1967-10-27,50.00,50.000
9,Standby Arrangement,1990-07-20,100.00,48.000
10,Standby Arrangement,1992-01-31,91.98,18.396
11,Standby Arrangement,1985-09-12,200.00,10.000
12,Standby Arrangement,1969-12-15,25.00,10.000
13,Standby Arrangement,1968-10-27,27.00,10.000
14,Standby Arrangement,1971-03-18,30.00,8.250

### **Question 7 : Arrangements de courte durée (< 1 an)**

In [24]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q7 = """
SELECT facility, date_of_arrangement, expiration_date,
       CAST((julianday(expiration_date) - julianday(date_of_arrangement)) AS INT) AS duration_days
FROM facilities
WHERE (julianday(expiration_date) - julianday(date_of_arrangement)) < 365
ORDER BY duration_days;
"""
display(pd.read_sql_query(q7, conn))
conn.close()

                 facility date_of_arrangement expiration_date  duration_days
0  Extended Fund Facility          1980-10-08      1981-03-08            151
1     Standby Arrangement          1990-07-20      1991-03-31            254
2     Standby Arrangement          1982-04-26      1983-04-25            364
3     Standby Arrangement          1969-12-15      1970-12-14            364
4     Standby Arrangement          1968-10-27      1969-10-26            364
5     Standby Arrangement          1966-09-23      1967-09-22            364
6     Standby Arrangement          1965-09-23      1966-09-22            364

### **Question 8 : Taux de tirage par type de facilité et par décennie**

In [25]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q8 = """
SELECT facility,
       (strftime('%Y', date_of_arrangement) / 10) * 10 AS decade,
       ROUND(SUM(amount_drawn), 2) AS total_drawn,
       ROUND(SUM(amount_agreed), 2) AS total_agreed,
       ROUND((SUM(amount_drawn) / SUM(amount_agreed)) * 100, 2) || '%' AS draw_rate_pct
FROM facilities
GROUP BY facility, decade
ORDER BY decade ASC, facility;
"""
display(pd.read_sql_query(q8, conn))
conn.close()

,facility,decade,total_drawn,total_agreed,draw_rate_pct
0,Standby Arrangement,1950,0.00,25.00,0.0%
1,Standby Arrangement,1960,70.00,197.00,35.53%
2,Standby Arrangement,1970,8.25,30.00,27.5%
3,Extended Fund Facility,1980,283.50,1627.05,17.42%
4,Standby Arrangement,1980,1031.25,1221.25,84.44%
5,Standby Arrangement,1990,66.40,191.98,34.58%
6,Precautionary and Liquidity Line,2010,2150800.00,12007300.00,17.91%
7,Flexible Credit Line,2020,0.00,7176200.00,0.0%
8,Resilience and Sustainability Facility,2020,937.50,1000000.00,0.09%

### **Question 9 : Arrangements sans aucun montant restant (outstanding = 0)**

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q9 = """
SELECT facility, date_of_arrangement, amount_agreed, amount_drawn, amount_outstanding
FROM facilities
WHERE amount_outstanding = 0;
"""
display(pd.read_sql_query(q9, conn))
conn.close()

### **Question 10 : Top 10 des montants accordés les plus élevés**

In [26]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/imf_facilities.db')

q10 = """
SELECT facility, date_of_arrangement, amount_agreed
FROM facilities
ORDER BY amount_agreed DESC
LIMIT 10;
"""
display(pd.read_sql_query(q10, conn))
conn.close()

                                 facility date_of_arrangement  amount_agreed
0        Precautionary and Liquidity Line          2012-08-03     4117400.00
1                    Flexible Credit Line          2023-04-03     3726200.00
2                    Flexible Credit Line          2025-04-02     3450000.00
3        Precautionary and Liquidity Line          2014-07-28     3235100.00
4        Precautionary and Liquidity Line          2016-07-22     2504000.00
5        Precautionary and Liquidity Line          2018-12-17     2150800.00
6  Resilience and Sustainability Facility          2023-09-28     1000000.00
7                  Extended Fund Facility          1981-03-09         817.05
8                  Extended Fund Facility          1980-10-08         810.00
9                     Standby Arrangement          1983-09-16         300.00